version = 0.1
[default.deploy.parameters]
stack_name = "boombots-stats"
resolve_s3 = true
s3_prefix = "boombots-stats"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
